### DISCUSSION TITLE
anki hiding furigana

### DISCUSSION THREAD

**Discussion by ivanbrugere** [SethClydesdale/genki-study-resources#128] [Questions] [answered]
The anki cards include the furigana which really hinders my learning. Is there a way to use a different template which has mouse-over reveal of furigana?

**Comment by SethClydesdale** [comment, marked as answer]
Hello @ivanbrugere!

You should be able to customize styling by going to the deck, click "browse" at the top, then select the deck, click "cards...," and go to the "styling" tab. Here you can replace:
```css
ruby rt { color:#777; }
ruby:hover rt { color:#333; }
```

with:
```css
ruby rt { color:#777; opacity:0; }
ruby:hover rt { color:#333; opacity:1; }
```

Save and you're done!

I agree that furigana can be a hinderance when it comes to memorizing the kanji variant of a word, so I may update the decks to include this style rule. Will look into adding a visual cue though so the student knows they can hover to reveal the kana.
