### ISSUE TITLE
Anki deck- includes kanji far beyond the learner's level.

### ISSUE THREAD

**Issue by ilar** [SethClydesdale/genki-study-resources#269]
Genki seems to introduce some kanji just as a preview of sorts- kanji that you are absolutely not expected to know or memorize, e.g. 誕生日. The anki decks associated with each lesson seem to treat these kanji/phrases/etc as things you're expected to memorize and know, despite them involving kanji far above the Genki 1/2 level.

They should probably be removed from the decks.

Edit: alternatively  the furigana could be always shown for those kanji instead of hidden by default to match the genki books as well.

**Comment by remique** [comment]
I had the same issue with kanji and I resolved it by changing the styling of the deck. 

<img width="1050" alt="Zrzut ekranu 2024-06-7 o 13 45 08" src="https://github.com/SethClydesdale/genki-study-resources/assets/44347542/45717c50-29b7-456f-9493-4ab1aa3dc5e8">

It isn't perfect, but good enough for me and I feel like I am finally learning the vocabulary while familiarizing myself with more advanced kanji. 

To do this: open `Edit` -> Click `Cards` -> In Template check `Styling` and change the styling.I am using night mode, so I changed the values for nightmode only. You can adjust the values to your liking.
```css
/* Night Mode CSS */
.nightMode hr { border-color:#555; }
.nightMode ruby rt {
  color:#AAA;
  background:none;
  border-color:transparent;
}
.nightMode ruby:hover rt {
  color:#AAA;
  background:none;
  border-color:transparent;
}
.nightMode.card {
  color:#CCC;
  background-color:#222;
}
```
